variables:
  PRJ_NAME: webapp

  PRJ_DIR: /var/www/html/vue_boilerplate_2024
  DEV_DIR: $PRJ_DIR/dev/$PRJ_NAME
  TEST_DIR: $PRJ_DIR/tst/$PRJ_NAME

  ZIP_NAME: vue-boilerplate-prd

stages:
  - build
  - zip
  - deploy

# ###########################
#     DEV - LINUX           #
# ###########################

vue-boilerplate:dev:
  stage: build
  before_script:
    - node -v
    - 'if [ ! -d $DEV_DIR ]; then echo "$DEV_DIR does not exist" ; exit 1 ; fi'
    - npm install --progress=false
  script:
    - npm run build:dev
    - rm -rf .git
    - 'if [ -d $DEV_DIR/dist ]; then rm -rf $DEV_DIR/dist ; fi'
    - cp -Rf dist/ $DEV_DIR
  only:
    refs:
      - develop
      - /^feature\/.*$/
      - /^hotfix\/.*$/
    variables:
      - $CI_COMMIT_MESSAGE =~ /^dev\d+\.\d+\.\d+/
  tags:
    - web_dev

# ###########################
#     TEST - LINUX          #
# ###########################

vue-boilerplate:test:
  stage: build
  before_script:
    - node -v
    - 'if [ ! -d $TEST_DIR ]; then echo "$TEST_DIR does not exist" ; exit 1 ; fi'
    - npm install --progress=false
  script:
    - npm run build:tst
    - rm -rf .git
    - 'if [ -d $TEST_DIR/dist ]; then rm -rf $TEST_DIR/dist ; fi'
    - cp -Rf dist/ $TEST_DIR
  only:
    refs:
      - release
      - web
    variables:
      - $CI_BUILD == "testing"
  tags:
    - web_dev

# ###########################
#    STG/PRD - LINUX57      #
# ###########################

vue-boilerplate:zip:build:
  stage: build
  variables:
    DOWNLOAD_DIR: /var/www/html/DOWNLOAD
  before_script:
    - node -v
    - npm install --progress=false
  script:
    - npm run build
    - zip -qr $ZIP_NAME-$CI_COMMIT_REF_NAME.zip ./dist
    - mv $ZIP_NAME-$CI_COMMIT_REF_NAME.zip $DOWNLOAD_DIR
  artifacts:
    expire_in: 1 day
    paths:
      - dist
  only:
    refs:
      - master
      - web
    variables:
      - $CI_BUILD =~ /^v\d+\.\d+\.\d+$/
  tags:
    - web_dev
